version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pasa la variable de entorno para que Vite la integre en la compilación
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    container_name: react_frontend
    ports:
      - "2001:2001"
    environment:
      - NODE_ENV=production
      - PORT=2001
    restart: unless-stopped
    # Si quisieras poner configuraciones de red, las podrías agregar aquí
