services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-https://apitiendaprueba.ratelapps.com}  # URL de tu API
    container_name: mi-frontend
    ports:
      - "2002:80"  # Puerto diferente al backend (ej: 2001 era el back)
    restart: unless-stopped